Dependancies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import skew, kurtosis

Logic to analysis the dataset.

In [4]:
#load dataset 
telco_df = pd.read_csv('D:/Customer_Churn_Prediction/data/unprocessed_data/telco_customer_data_v2.csv') 
telco_df.shape

(70000, 21)

Infos on data

In [ ]:
telco_df.info()

In [23]:
display(telco_df.head(),telco_df.tail())

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST00001,Male,0,No,Yes,3.0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,68.61,205.83,Yes
1,CUST00002,Male,1,Yes,No,2.0,Yes,Yes,DSL,No,...,No internet service,Yes,NaN,No,One year,Yes,Bank transfer (automatic),23.15,46.3,No
2,CUST00003,Female,No,No,No,42.0,Yes,Yes,DSL,No,...,No,NaN,Yes,Yes,Month-to-month,No,Electronic check,42.63,1790.46,Yes
3,CUST00004,Female,0,No,Yes,40.0,Yes,Yes,Fiber optic,No,...,Yes,No,No,No internet service,Month-to-month,No,Electronic check,75.04,3001.6,No
4,CUST00005,Male,Yes,Yes,Yes,17.0,Yes,NaN,Fiber optic,Yes,...,Yes,No,No internet service,No,Two year,Yes,Electronic check,22.38,380.46,Yes

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
69995,CUST69996,Male,1,Yes,Yes,30.0,Yes,Yes,Fiber optic,Yes,...,No,Yes,No,No,Two year,No,Electronic check,74.85,2245.5,No
69996,CUST69997,Male,0,Yes,NaN,15.0,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),40.67,610.05,Yes
69997,CUST69998,Male,0,NaN,No,20.0,Yes,No,DSL,Yes,...,No,No,NaN,No,Month-to-month,Yes,Mailed check,29.44,588.8,No
69998,CUST69999,Male,0,No,No,21.0,Yes,No,Fiber optic,No,...,No,No,Yes,No internet service,Month-to-month,Yes,Electronic check,46.77,982.17,No
69999,CUST70000,Female,0,No,No,3.0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Electronic check,72.41,217.23,Yes

overall statistical

In [ ]:
#defined a function to summarize dataset

def statiscal_summary(df):
    #instancy a table to store the data
    summary_data =[]
        #iterate in all columns in the df
    for col in df.columns:
        #assign it to a col_data(store a column data)
        col_data = df[col]
        col_summary = {
            "Column":col,
            "Data Type":col_data.dtype,
            "Non-Null Count": col_data.notnull().sum(),
            "Missing Count": col_data.isnull().sum(),
            "Missing %": col_data.isnull().mean() * 100,
            "Unique Count": col_data.nunique()
        }

        #check if columns is numeral type or non
        if pd.api.types.is_numeric_dtype(col_data):
            col_summary.update({
                "Min": col_data.min(),
                "Max": col_data.max(),
                "Mean": col_data.mean(),
                "Median": col_data.median(),
                "Std Dev": col_data.std(),
                "Skewness": skew(col_data.dropna()),
                "Kurtosis": kurtosis(col_data.dropna())
            })
        else:
            mode = col_data.mode().iloc[0] if not col_data.mode().empty else np.nan
            mode_freq = col_data.value_counts().iloc[0] if not col_data.value_counts().empty else np.nan
            col_summary.update({
                "Top (Mode)": mode,
                "Freq": mode_freq
            })

        summary_data.append(col_summary)

    
    return pd.DataFrame(summary_data).style.format(precision=2).background_gradient(cmap="Blues")

In [25]:
summary = statiscal_summary(telco_df)
summary

In [ ]:
df_good_features = telco_df[["tenure","Contract","MonthlyCharges","TotalCharges","InternetService","PaymentMethod","TechSupport","OnlineSecurity","Churn"]]
df_good_features

Checking value count in each columns and see which value mean the same thing

In [ ]:
#df_good_features["PaymentMethod"].value_counts()
#df_good_features["Churn"].value_counts()
#df_good_features["Contract"].value_counts()
#df_good_features["OnlineSecurity"].value_counts()
#df_good_features["TechSupport"].value_counts()

In [112]:
df_good_features["Churn"] = df_good_features["Churn"].replace({
    "NO CHURN": "NO",
    "N" :"NO",
    "No":"NO",
    "Yes":"YES",
    "CHURNED":"YES",
    "Y":"YES"
    
})

df_good_features["Churn"].value_counts()

C:\Users\StrixROGStartyourPC\AppData\Local\Temp\ipykernel_21292\4183003059.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_good_features["Churn"] = df_good_features["Churn"].replace({

Churn
NO         37148
YES        32798
Unknown       54
Name: count, dtype: int64

In [ ]:
df_good_features["PaymentMethod"] = df_good_features["PaymentMethod"].replace({
    "BANK TRANSFER":"Bank transfer (automatic)"
})

In [ ]:
df_good_features["Contract"] = df_good_features["Contract"].replace({
    "M-M":"Month-to-month"
})

In [ ]:
df_good_features["OnlineSecurity"] = df_good_features["OnlineSecurity"].replace({

    "No internet service":"No",
    "True":"Yes",
    "Y":"Yes"
})

df_good_features["TechSupport"] = df_good_features["TechSupport"].replace({
 
    "No internet service":"No",
    "True":"Yes",
    "Y":"Yes"
})

In [ ]:
df_good_features["TotalCharges"].value_counts()